"""Initial migration

Revision ID: a85c234a5dcc
Revises: 
Create Date: 2024-06-29 12:14:02.472381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85c234a5dcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admins_ids_str', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__config'))
    )
    op.create_table('languages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__languages'))
    )
    op.create_index(op.f('ix__languages__code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix__languages__id'), 'languages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('tg_first_name', sa.String(), nullable=True),
    sa.Column('tg_last_name', sa.String(), nullable=True),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk__users__language_code__languages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__chats__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__chats'))
    )
    op.create_index(op.f('ix__chats__chat_id'), 'chats', ['chat_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__payments__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__payments'))
    )
    op.create_table('translations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk__translations__language_code__languages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__translations__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__translations'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk__subscriptions__payment_id__payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__subscriptions__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__subscriptions')),
    sa.UniqueConstraint('payment_id', name=op.f('uq__subscriptions__payment_id'))
    )
    op.create_index(op.f('ix__subscriptions__id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__subscriptions__id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('translations')
    op.drop_table('payments')
    op.drop_index(op.f('ix__chats__chat_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix__languages__id'), table_name='languages')
    op.drop_index(op.f('ix__languages__code'), table_name='languages')
    op.drop_table('languages')
    op.drop_table('config')
    # ### end Alembic commands ###
